service: large-project-layout

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1

package:
  # By default, exclude everything (include in individual functions)
  individually: true
  exclude:
    - "**"

functions:
  api-meetups:
    handler: api/meetups/index.route
    events:
      - http:
          path: api/meetups/
          method: get
      - http:
          path: api/meetups/{meetup}
          method: get
      - http:
          path: api/meetups/
          method: post
    package:
      include:
        - api/meetups/**

  # api-subscriptions-post:
  #   handler: api/subscriptions/index.post
  #     - http:
  #       path: api/subscriptions/
  #       method: post
  #
  # api-subscriptions-list:
  #   handler: api/subscriptions/index.list
  #     - http:
  #       path: api/subscriptions/
  #       method: get
  #
  # webhooks-slack-links-post:
  #   handler: webhooks/slack/index.post
  #     - http:
  #         path: webhooks/slack/
  #         method: post
  #
  # awshooks-subscription-filter:
  #   handler: awshooks/subscription-filter/index.handle
  #
  # web:
  #   handler: web/index.get
  #     - http:
  #         path: /{proxy+}
